### ISSUE TITLE
Rename "master" to "main"

### ISSUE THREAD

**Issue by ambv** [python/codespeed#28]
There is currently a hack to allow continued use of "master" as a branch for new uploaded results. This needs to go away. We've been using "main" for years.

**Comment by mattip** [comment]
PyPy also came across this: we recently moved from Mercurial (default branch: "default") to Git (default branch: "main"). Unfortunately on the admin/project page, each project can only have one default branch. This means that we now need to choose whether to show Git results on the Timeline and Changes tabs for these projects, or to show Mercurial results. So it would be nice if there could be more than one default branch (a bit of an oxymoron). Then CPython could upload `main` results but still see the `master` ones as well.

**Comment by diegorusso** [comment]
We need to get to the bottom of it as this issues is preventing aarch64 results to be shown.

**Comment by mattip** [comment]
Which tab is not presenting aarch64 results?
It appears the filtering happens [here](https://github.com/python/codespeed/blob/263860bc298fd970c8466b3161de386582e4f801/codespeed/views.py#L433) for the timeline tab.

**Comment by diegorusso** [comment]
it is in the "changes" and "timeline" tabs. In the comparison tab, although not great) you have a way to select the branch via the executable.
Moving from Mercurial to Git can be done by creating a new project that points to the right mercurial or git repo. In this way you have a clean break to what is in mercurial and in git.
Instead in the case of git/master -> git->main, we just need to change the data in the database: all results related to master needs to be changed to main branch. This is "simply" a database query to update such data. Commits sha won't be changing if we change the branch name and everything will keep working as expected.

Once we have fixed the master/main issue, we should update the UI to allow the user to select branches explicitly in all three tabs (related issue https://github.com/python/codespeed/issues/27) Instead of assuming the "default" branch we let the user what branch they want to see. If the user doesn't specify anything we can assume it will be "main" for git.

Thoughts?

**Comment by ambv** [comment]
Fixed, thanks, Diego!
